name: theway
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on the way
      uses: appleboy/ssh-action@master
      with:
        host: 3.127.35.222
        username: root
        key: ${{ secrets.TW_SECRET }}
        port: 22
        script: |
          cd /opt/theway
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i '/Made with Pingendo Free/d' index.html
          sed -i 's/<html>/<html lang="en">/' index.html
