name: theway
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on the way
      uses: appleboy/ssh-action@master
      with:
        host: 3.127.35.222
        username: webuser
        key: ${{ secrets.TW_SECRET }}
        port: 22
        script: |
          cd /opt/theway
          git log -1
          git pull
